### ISSUE TITLE
onMessage() callback not called when event starts with a comment

### ISSUE THREAD

**Issue by autresrhumbs** [heremaps/oksse#19]
Hello,

When receiving an event starting with a comment line, onComment() is called, but onMessage() is not.

Example of received event:

```
: This is a comment line
id: 0
event: EventType
data: text
```

Do you know what could be wrong?

Thanks!

**Comment by autresrhumbs** [comment]
Exactly.
The onComment is called with the string "This is a comment line", but the onMessage does not seem to be called for the rest of the event.

**Comment by autresrhumbs** [comment]
I think I found the issue, which is on the server side...
It misses one extra line at the end of the event.
So, : 
`This is a comment line\nid: 0\nevent: EventType\ndata: text\n  **<-- additional \n missing here**`

Am I correct?
If so, I guess we can close this issue...

**Comment by skimarxall** [comment]
Yes thats issue, without the end line the message does not finish.
