### ISSUE TITLE
onRetryErrror(). Reoccurring EOFException.

### ISSUE THREAD

**Issue by marcel-eggum** [heremaps/oksse#8]
I constantly receive an EOFException in the onRetryError handler.
This happens about 60 seconds after the connection is established and onOpen() has been called.
We manage to receive 1-2 messages before we encounter the exception.

I was just wondering if there is something I can do to prevent this behaviour as I often have to reconnect to our SSE server.

We are wondering if this is an issue on our side, or if we should look closer into oksse itself.

The stack trace itself reads:
```
java.io.EOFException
    at okio.RealBufferedSource.require(RealBufferedSource.java:60)
    at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:294)
    at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:458)
    at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:438)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
    at com.here.oksse.RealServerSentEvent$Reader.read(RealServerSentEvent.java:181)
    at com.here.oksse.RealServerSentEvent.openSse(RealServerSentEvent.java:89)
    at com.here.oksse.RealServerSentEvent.access$100(RealServerSentEvent.java:26)
    at com.here.oksse.RealServerSentEvent$1.onResponse(RealServerSentEvent.java:75)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)
```
In essence, our client setup in performed in the following way:
```
OkSse okSse = new OkSse();

Request request = new Request.Builder()
                    .url(url)
                    .addHeader("Authorization", auth.getToken())
                    .build();

sse = okSse.newServerSentEvent(request, callback);
```

For reference, the SSE Listener `callback`, is implemented in the following way:

```
ServerSentEvent.Listener callback = new ServerSentEvent.Listener() {
        @Override
        public void onOpen(ServerSentEvent sse, Response response) {
            Timber.d("onOpen()");
            state = State.CONNECTED;
        }

        @Override
        public void onMessage(ServerSentEvent sse, String id, String event, String message) {
            if (message != null && !message.isEmpty()) {
                    listener.onMessage(event, message);
            }
        }

        @WorkerThread
        @Override
        public void onComment(ServerSentEvent sse, String comment) {
            // When a comment is received
        }

        @WorkerThread
        @Override
        public boolean onRetryTime(ServerSentEvent sse, long milliseconds) {
            return true; // True to use the new retry time received by SSE
        }

        @WorkerThread
        @Override
        public boolean onRetryError(ServerSentEvent sse, Throwable throwable, Response response) {
            Timber.e("onRetryError err = " + throwable + ", res = " + response);

            listener.onError(throwable);

            return true; // True to retry, false otherwise
        }

        @Override
        public Request onPreRetry(ServerSentEvent sse, Request originalRequest) {
            return originalRequest;
        }

        @WorkerThread
        @Override
        public void onClosed(ServerSentEvent sse) {
            Timber.d("onClosed");
            sse = null;

            if (listener != null) {
                listener.onClose();
            }
        }

    };
```

**Comment by skimarxall** [comment]
Hi looking at the stack trace seems that the error comes when reading from the SSE channel, this means that is receiving sth that cause an EOF. Does not look that you are doing something wrong on the client, neither the OkSse

Do you have access to the response from the server or a way to read what is sending? 

How long it takes from the first read till you get the exception? I am thinking that maybe the OkHttpclient is closing the channel if it does not read anything for some time.

Although this should not be the cases since you are using the default constructor 
```java
    public OkSse() {
        this(new OkHttpClient.Builder().readTimeout(0, TimeUnit.SECONDS).retryOnConnectionFailure(true).build());
    }
```

**Comment by marcel-eggum** [comment]
It takes exactly 60 seconds before we see the EOFException. Every time.
This almost makes me think that this may be a configuration issue.

I checked the response that we receive as I was wondering if it may have contained anomalies, but it checks out.

The message format looks like this:
```
event: "string id"
data: {"foo": "bar", "bar": "foo"}
```

The response headers from the server seem correct as well:
```
HTTP/1.1 200
Cache-Control: private
Content-Encoding: gzip
Content-Type: text/event-stream;charset=UTF-8
Date: Sat, 07 Oct 2017 11:05:11 GMT
Expires: Thu, 01 Jan 1970 00:00:00 UTC
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
transfer-encoding: chunked
Connection: keep-alive
```

I do however wonder if the `expires` header affects OkHttp in some way.

**Comment by skimarxall** [comment]
OkHttp respects the headers so it might be causing it to disconnect. But what you could do is to take any other URL feed that serves an SSE channel and check your code.

Try the feed we use for the tests: https://proxy.streamdata.io/https://api.myjson.com/bins/jixid

It only send one message but I should not close the channel if it does close it then sth is wrong on the configuration of the client

**Comment by skimarxall** [comment]
Oh, also I just saw the content comes gzip? That might cause issues, I remember we had some issues with it.

**Comment by marcel-eggum** [comment]
Thank you for the answers.
The source that you provided seems stable. No EOFExceptions occurred within the timeframe.

I will check back with our team and try to adjust our headers and encoding.
Il post the solution as soon as we find it for future reference.

**Comment by skimarxall** [comment]
Any news on this? Can I close the ticket?

**Comment by marcel-eggum** [comment]
Indeed.

Our server config. indicated that the connection should not be kept alive for more than a minute.
Additionally, we added a "keepAlive" message that is sendt to the client every x seconds.

In summary. This was a configuration error on the backend.
