### ISSUE TITLE
HTTPS Not secure problem

### ISSUE THREAD

**Issue by ognjenmarcheta** [heremaps/oksse#9]
I'm working on app where url is on https but certificate is not valid. How can i bypass this for now until they fix their https?

java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by ognjenmarcheta** [comment]
Ok i solved this by modifying client to trust all certs. Now i get error:
 onRetryError: Read timed out after successful connection.

**Comment by ognjenmarcheta** [comment]
Fixed i forgot to include this in builder:
builder.readTimeout(0, TimeUnit.SECONDS);
builder.retryOnConnectionFailure(true);

**Comment by skimarxall** [comment]
Great, I like to read issues that are closed itself :P

That's the main point of offering just a wrapper over the okhttp, that you can pass your own instance and have the flexibility and configuration of okhttp.
